#!/usr/bin/env python3
# Copyright (c) 2015 Severen Redwood <severen.redwood@gmail.com>
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

import os
import sys
import multiprocessing

buildDir = 'target/build'
if not os.path.exists(buildDir):
    print('Please run script/configure first!')
    sys.exit(1)

os.chdir(buildDir)
os.system('make -j{}'.format(multiprocessing.cpu_count()))
